### PR TITLE
add downloaders name to metadata of datagrid export

### PR DESCRIPTION
**Pull request by qu-bit1**
To prevent data being shared by some people :(

- Remove csv and print export option
- now data is downloaded in xlsx format, with downloader's name being embedded to the metadata of the file

### CODE REVIEW

**Comment by utkarsh-tf141** [comment]
Add the userID as well

**Comment by utkarsh-tf141** [comment]
Try to change the file name as the meta title of the page @qu-bit1. Rest is fine

**Comment by qu-bit1** [comment]
@utkarsh-tf141 i tried doing that using `window.location.pathname`, as window was undefined when reloading some pages, so the if condition I used was breaking the website, any other way to do that?

**Comment by utkarsh-tf141** [comment]
Try using useRouter

**Pull request merged**
