### PR TITLE
Remove static  headers and add exam mapper

### PR DESCRIPTION
**Pull request by ManasGupta1310**

### CODE REVIEW

**Comment by 1-Harshit** [comment]
Dual,double major is also JEE

**Comment by 1-Harshit** [comment]
mark entire BT/B/DUALA/B/C/Double from JEE

**Comment by 1-Harshit** [comment]
have u implemented calender in students side?

**Comment by ManasGupta1310** [comment]
> have u implemented calender in students side?

Yes

**Comment by ManasGupta1310** [comment]
> mark entire BT/B/DUALA/B/C/Double from JEE No need to take branch input I guess

Can you confirm this?

**Comment by ManasGupta1310** [comment]
Also while you are at it just take  a look at other exams also.

**Comment by itsGyanendra** [comment]
JEE - BT/ BS/DUAL/Double Major
Gate - MTech/MSR/Design (MDes)
CAT - MBA
CEED - MDes
JAM - MSc

**Pull request merged**
