### PR TITLE
updated notice tables

### PR DESCRIPTION
**Pull request by amdpt323**
media query is not set yet

### CODE REVIEW

**Comment by ManasGupta1310** [comment]
@amdpt323 deploy link?

**Comment by amdpt323** [comment]
- closes #16

**Comment by amdpt323** [comment]
https://ras-frontend-git-fork-amdpt323-noticetables-abhishekshree.vercel.app/admin/rc/542/notice

**Comment by ManasGupta1310** [comment]
Good enough! Merging now

**Pull request merged**
