### PR TITLE
Shimmer loader3

### PR DESCRIPTION
**Pull request by ahujatejas06**
Shimmer Loader added

With reference to issue #10

### CODE REVIEW

**Comment by ahujatejas06** [comment]
This is somehow compiling locally with no errors.... checking deployment

**Comment by 1-Harshit** [comment]
@ManasGupta1310 do you want this type of shimmer loader? or something different?

**Comment by 1-Harshit** [comment]
@ahujatejas06 work on different PR
Behavior and placement of shimmer is not clear yet

Also you should claim the issue before working on it, or create one if there is none

**Comment by 1-Harshit** [comment]
💯 on efforts

**Comment by ManasGupta1310** [comment]
Closing this PR. Done in other PR.

**Pull request closed without merging**
