### PR TITLE
Final QnA

### PR DESCRIPTION
**Pull request by utkarsh-tf141**

### CODE REVIEW

**Comment by utkarsh-tf141** [comment]
- closes #24

**Comment by utkarsh-tf141** [comment]
URL: admin/rc/1/proforma/1/question/1

**Comment by ManasGupta1310** [comment]
Please use grid and stack instead of table

Refer for form structure here: https://github.com/spo-iitk/ras-frontend/blob/main/pages/student/rc/%5BrcId%5D/enroll.tsx

Just take reference of the structure from the link here. You may copy the code and just change the values as  required.
Also use texfield variant as "standard"

**Comment by ManasGupta1310** [comment]
Alright merging now!

**Pull request merged**
