### PR TITLE
comlete issue 38

### LINKED ISSUE #38: [Admin UI] Master student dashboard
[Admin page 68](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/:id`

[Admin page 69](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/:id/details`

[Admin page 70](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/:id/rc/:id`

### PR DESCRIPTION
**Pull request by amdpt323**
- closes #38

### CODE REVIEW

**Comment by ManasGupta1310** [comment]
Why is it the same table on all the three pages?
Is it so in the Figma too? @amdpt323

**Comment by amdpt323** [comment]
@ManasGupta1310 yeah all the figma content are same

**Comment by ManasGupta1310** [comment]
@amdpt323 the content in figma for you issue is different. Please check once

**Comment by 1-Harshit** [comment]
Should we close this?

**Pull request closed without merging**
